import { mutation } from "./_generated/server";
import { v } from "convex/values";

export const seedSampleData = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if data already exists
    const existingTools = await ctx.db.query("aiTools").first();
    if (existingTools) {
      return "Sample data already exists";
    }

    const sampleTools = [
      // Writing & Content
      {
        name: "ChatGPT",
        description: "Advanced AI chatbot for conversations, writing assistance, and problem-solving across various domains.",
        url: "https://chat.openai.com",
        category: "Writing & Content",
        tags: ["chatbot", "writing", "AI assistant"],
        pricing: "freemium" as const,
        language: "en" as const,
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg",
        isApproved: true,
      },
      {
        name: "Grammarly",
        description: "AI-powered writing assistant that helps improve grammar, spelling, and writing style.",
        url: "https://grammarly.com",
        category: "Writing & Content",
        tags: ["grammar", "writing", "editing"],
        pricing: "freemium" as const,
        language: "en" as const,
        logoUrl: "https://static.grammarly.com/assets/files/efe57d016d9efff36da7884c193b646b/grammarly_logo_white.svg",
        isApproved: true,
      },
      {
        name: "Jasper AI",
        description: "AI content creation platform for marketing copy, blog posts, and creative writing.",
        url: "https://jasper.ai",
        category: "Writing & Content",
        tags: ["content creation", "marketing", "copywriting"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Copy.ai",
        description: "AI-powered copywriting tool for creating marketing content, emails, and social media posts.",
        url: "https://copy.ai",
        category: "Writing & Content",
        tags: ["copywriting", "marketing", "social media"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Writesonic",
        description: "AI writing assistant for creating articles, ads, landing pages, and product descriptions.",
        url: "https://writesonic.com",
        category: "Writing & Content",
        tags: ["writing", "articles", "ads", "product descriptions"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      
      // Image Generation
      {
        name: "DALL-E 3",
        description: "Advanced AI image generator that creates high-quality images from text descriptions.",
        url: "https://openai.com/dall-e-3",
        category: "Image Generation",
        tags: ["image generation", "AI art", "creative"],
        pricing: "paid" as const,
        language: "en" as const,
        logoUrl: "https://cdn.openai.com/API/logo-openai.svg",
        isApproved: true,
      },
      {
        name: "Midjourney",
        description: "AI art generator that creates stunning, artistic images from text prompts.",
        url: "https://midjourney.com",
        category: "Image Generation",
        tags: ["AI art", "image generation", "creative"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Stable Diffusion",
        description: "Open-source AI model for generating detailed images from text descriptions.",
        url: "https://stability.ai",
        category: "Image Generation",
        tags: ["open source", "image generation", "AI art"],
        pricing: "free" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Leonardo AI",
        description: "AI-powered creative suite for generating production-quality visual assets.",
        url: "https://leonardo.ai",
        category: "Image Generation",
        tags: ["AI art", "creative assets", "production"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Adobe Firefly",
        description: "Adobe's AI-powered creative tools for generating images, text effects, and more.",
        url: "https://firefly.adobe.com",
        category: "Image Generation",
        tags: ["Adobe", "creative tools", "text effects"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      
      // Code & Development
      {
        name: "GitHub Copilot",
        description: "AI pair programmer that helps write code faster with intelligent suggestions.",
        url: "https://github.com/features/copilot",
        category: "Code & Development",
        tags: ["coding", "programming", "development"],
        pricing: "paid" as const,
        language: "en" as const,
        logoUrl: "https://github.githubassets.com/images/modules/site/copilot/copilot.png",
        isApproved: true,
      },
      {
        name: "Cursor",
        description: "AI-powered code editor built for pair programming with AI.",
        url: "https://cursor.sh",
        category: "Code & Development",
        tags: ["code editor", "AI programming", "development"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Replit AI",
        description: "AI coding assistant integrated into the Replit online IDE.",
        url: "https://replit.com",
        category: "Code & Development",
        tags: ["IDE", "coding", "AI assistant"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Tabnine",
        description: "AI code completion tool that predicts and suggests your next lines of code.",
        url: "https://tabnine.com",
        category: "Code & Development",
        tags: ["code completion", "AI assistant", "productivity"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "CodeT5",
        description: "AI model for code understanding and generation tasks.",
        url: "https://github.com/salesforce/CodeT5",
        category: "Code & Development",
        tags: ["code generation", "open source", "machine learning"],
        pricing: "free" as const,
        language: "en" as const,
        isApproved: true,
      },
      
      // Video & Audio
      {
        name: "Runway ML",
        description: "AI-powered creative suite for video editing, generation, and enhancement.",
        url: "https://runwayml.com",
        category: "Video & Audio",
        tags: ["video editing", "AI video", "creative"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "ElevenLabs",
        description: "AI voice generator and text-to-speech with realistic voice cloning.",
        url: "https://elevenlabs.io",
        category: "Video & Audio",
        tags: ["voice synthesis", "text-to-speech", "audio"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Descript",
        description: "AI-powered video and podcast editing with transcription and voice synthesis.",
        url: "https://descript.com",
        category: "Video & Audio",
        tags: ["video editing", "podcast", "transcription"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Synthesia",
        description: "AI video generation platform for creating professional videos with AI avatars.",
        url: "https://synthesia.io",
        category: "Video & Audio",
        tags: ["AI avatars", "video generation", "professional"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Murf AI",
        description: "AI voice generator for creating realistic voiceovers and narrations.",
        url: "https://murf.ai",
        category: "Video & Audio",
        tags: ["voiceover", "narration", "text-to-speech"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      
      // Business & Productivity
      {
        name: "Notion AI",
        description: "AI writing assistant integrated into Notion for enhanced productivity.",
        url: "https://notion.so/product/ai",
        category: "Business & Productivity",
        tags: ["productivity", "writing", "organization"],
        pricing: "freemium" as const,
        language: "en" as const,
        logoUrl: "https://www.notion.so/cdn-cgi/image/format=webp,width=256/https://www.notion.so/images/logo-ios.png",
        isApproved: true,
      },
      {
        name: "Zapier AI",
        description: "AI-powered automation platform for connecting apps and workflows.",
        url: "https://zapier.com",
        category: "Business & Productivity",
        tags: ["automation", "workflow", "integration"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Calendly AI",
        description: "AI-enhanced scheduling assistant for meeting coordination.",
        url: "https://calendly.com",
        category: "Business & Productivity",
        tags: ["scheduling", "meetings", "productivity"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Monday.com AI",
        description: "AI-powered project management and team collaboration platform.",
        url: "https://monday.com",
        category: "Business & Productivity",
        tags: ["project management", "collaboration", "workflow"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Otter.ai",
        description: "AI meeting assistant that records, transcribes, and summarizes meetings.",
        url: "https://otter.ai",
        category: "Business & Productivity",
        tags: ["meeting transcription", "note-taking", "collaboration"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      
      // Data & Analytics
      {
        name: "Tableau AI",
        description: "AI-powered data visualization and business intelligence platform.",
        url: "https://tableau.com",
        category: "Data & Analytics",
        tags: ["data visualization", "analytics", "business intelligence"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "DataRobot",
        description: "Automated machine learning platform for predictive analytics.",
        url: "https://datarobot.com",
        category: "Data & Analytics",
        tags: ["machine learning", "predictive analytics", "automation"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "H2O.ai",
        description: "Open-source machine learning and AI platform for data scientists.",
        url: "https://h2o.ai",
        category: "Data & Analytics",
        tags: ["machine learning", "open source", "data science"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Julius AI",
        description: "AI data analyst that helps analyze and visualize your data with natural language.",
        url: "https://julius.ai",
        category: "Data & Analytics",
        tags: ["data analysis", "natural language", "visualization"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Polymer",
        description: "AI-powered business intelligence tool for creating dashboards and insights.",
        url: "https://polymer.co",
        category: "Data & Analytics",
        tags: ["business intelligence", "dashboards", "insights"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },

      // Design & Creative
      {
        name: "Canva AI",
        description: "AI-powered design platform for creating graphics, presentations, and marketing materials.",
        url: "https://canva.com",
        category: "Design & Creative",
        tags: ["graphic design", "presentations", "marketing"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Figma AI",
        description: "AI features in Figma for enhanced design workflows and automation.",
        url: "https://figma.com",
        category: "Design & Creative",
        tags: ["UI design", "prototyping", "collaboration"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Looka",
        description: "AI logo maker and brand identity platform for businesses.",
        url: "https://looka.com",
        category: "Design & Creative",
        tags: ["logo design", "branding", "business"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Uizard",
        description: "AI-powered design tool that transforms sketches into digital designs.",
        url: "https://uizard.io",
        category: "Design & Creative",
        tags: ["UI design", "prototyping", "sketch-to-design"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Khroma",
        description: "AI color tool that learns your preferences and generates color palettes.",
        url: "https://khroma.co",
        category: "Design & Creative",
        tags: ["color palettes", "design", "personalization"],
        pricing: "free" as const,
        language: "en" as const,
        isApproved: true,
      },

      // Marketing & Sales
      {
        name: "HubSpot AI",
        description: "AI-powered CRM and marketing automation platform.",
        url: "https://hubspot.com",
        category: "Marketing & Sales",
        tags: ["CRM", "marketing automation", "sales"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Persado",
        description: "AI platform for generating persuasive marketing language and copy.",
        url: "https://persado.com",
        category: "Marketing & Sales",
        tags: ["marketing copy", "persuasion", "language generation"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Drift",
        description: "AI-powered conversational marketing and sales platform.",
        url: "https://drift.com",
        category: "Marketing & Sales",
        tags: ["chatbots", "conversational marketing", "lead generation"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Salesforce Einstein",
        description: "AI-powered features integrated into Salesforce CRM platform.",
        url: "https://salesforce.com/products/einstein",
        category: "Marketing & Sales",
        tags: ["CRM", "sales intelligence", "predictive analytics"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Mailchimp AI",
        description: "AI-powered email marketing platform with smart recommendations.",
        url: "https://mailchimp.com",
        category: "Marketing & Sales",
        tags: ["email marketing", "automation", "recommendations"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },

      // Education & Learning
      {
        name: "Khan Academy AI",
        description: "AI-powered personalized learning platform for students.",
        url: "https://khanacademy.org",
        category: "Education & Learning",
        tags: ["personalized learning", "education", "students"],
        pricing: "free" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Duolingo AI",
        description: "AI-powered language learning app with personalized lessons.",
        url: "https://duolingo.com",
        category: "Education & Learning",
        tags: ["language learning", "personalized", "mobile app"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Coursera AI",
        description: "AI-enhanced online learning platform with course recommendations.",
        url: "https://coursera.org",
        category: "Education & Learning",
        tags: ["online courses", "recommendations", "professional development"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Socratic by Google",
        description: "AI-powered homework help app that explains concepts step-by-step.",
        url: "https://socratic.org",
        category: "Education & Learning",
        tags: ["homework help", "step-by-step", "students"],
        pricing: "free" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Quizlet AI",
        description: "AI-powered study tools and flashcards for effective learning.",
        url: "https://quizlet.com",
        category: "Education & Learning",
        tags: ["flashcards", "study tools", "memorization"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },

      // Healthcare & Wellness
      {
        name: "Ada Health",
        description: "AI-powered health assessment and symptom checker app.",
        url: "https://ada.com",
        category: "Healthcare & Wellness",
        tags: ["health assessment", "symptom checker", "medical AI"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Babylon Health",
        description: "AI-powered healthcare platform for consultations and health monitoring.",
        url: "https://babylonhealth.com",
        category: "Healthcare & Wellness",
        tags: ["telemedicine", "health monitoring", "consultations"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Headspace AI",
        description: "AI-enhanced meditation and mindfulness app for mental wellness.",
        url: "https://headspace.com",
        category: "Healthcare & Wellness",
        tags: ["meditation", "mindfulness", "mental health"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "MyFitnessPal AI",
        description: "AI-powered nutrition tracking and fitness app.",
        url: "https://myfitnesspal.com",
        category: "Healthcare & Wellness",
        tags: ["nutrition tracking", "fitness", "health"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Woebot",
        description: "AI-powered mental health chatbot for emotional support and therapy.",
        url: "https://woebot.io",
        category: "Healthcare & Wellness",
        tags: ["mental health", "chatbot", "therapy"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },

      // Finance & Accounting
      {
        name: "Mint AI",
        description: "AI-powered personal finance management and budgeting app.",
        url: "https://mint.com",
        category: "Finance & Accounting",
        tags: ["personal finance", "budgeting", "expense tracking"],
        pricing: "free" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "QuickBooks AI",
        description: "AI-enhanced accounting software for small businesses.",
        url: "https://quickbooks.intuit.com",
        category: "Finance & Accounting",
        tags: ["accounting", "small business", "bookkeeping"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Kensho",
        description: "AI-powered financial analytics and market intelligence platform.",
        url: "https://kensho.com",
        category: "Finance & Accounting",
        tags: ["financial analytics", "market intelligence", "investment"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Zest AI",
        description: "AI platform for credit underwriting and risk assessment.",
        url: "https://zest.ai",
        category: "Finance & Accounting",
        tags: ["credit scoring", "risk assessment", "lending"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Yodlee AI",
        description: "AI-powered financial data aggregation and insights platform.",
        url: "https://yodlee.com",
        category: "Finance & Accounting",
        tags: ["data aggregation", "financial insights", "banking"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },

      // Customer Service
      {
        name: "Zendesk AI",
        description: "AI-powered customer service platform with automated support.",
        url: "https://zendesk.com",
        category: "Customer Service",
        tags: ["customer support", "automation", "helpdesk"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Intercom AI",
        description: "AI-powered customer messaging platform with chatbots.",
        url: "https://intercom.com",
        category: "Customer Service",
        tags: ["customer messaging", "chatbots", "support"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "LivePerson AI",
        description: "AI-powered conversational commerce and customer engagement platform.",
        url: "https://liveperson.com",
        category: "Customer Service",
        tags: ["conversational AI", "customer engagement", "commerce"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Freshworks AI",
        description: "AI-enhanced customer experience platform with automation.",
        url: "https://freshworks.com",
        category: "Customer Service",
        tags: ["customer experience", "automation", "CRM"],
        pricing: "freemium" as const,
        language: "en" as const,
        isApproved: true,
      },
      {
        name: "Ada AI",
        description: "AI-powered customer service automation platform.",
        url: "https://ada.cx",
        category: "Customer Service",
        tags: ["customer service", "automation", "chatbots"],
        pricing: "paid" as const,
        language: "en" as const,
        isApproved: true,
      },
    ];

    // Insert all sample tools
    for (const tool of sampleTools) {
      await ctx.db.insert("aiTools", tool);
    }

    return `Successfully added ${sampleTools.length} sample AI tools across ${[...new Set(sampleTools.map(t => t.category))].length} categories`;
  },
});
